language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

# command to install dependencies
install:
  - pip install --upgrade setuptools
  - pip install -r requirements-dev.txt
  - pip install -e .
# script run flake8
before_script: flake8
# command to run tests
script:
  - py.test
